app_users/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('account/', AccountInfoView.as_view(), name='account'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('edit_customer_info/', CustomerEditView.as_view(), name='edit_info'),
    path('upbalance/', TopUpBalanceView.as_view(), name='upbalance'),
    path('pay_order/', PayOrderView.as_view(), name='pay_order')
]

djangoMarket/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n', include('django.conf.urls.i18n')),
    path('users/', include('app_users.urls')),
    path('', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from .views import MainPageView, ProductDetailView, StoreView, AddReview, \
    ProductFilterView, SearchView, AddToWishList, \
    AddToCart, DeleteFromCart

urlpatterns = [
    path('', MainPageView.as_view(), name='main_page'),
    path('add_to_wish/', AddToWishList.as_view(), name='add_to_wish'),
    path('add_to_cart/', AddToCart.as_view(), name='add_to_cart'),
    path('delete_from_cart/', DeleteFromCart.as_view(), name='delete_from_cart'),
    path('filter/', ProductFilterView.as_view(), name='filter'),
    path('search/', SearchView.as_view(), name='search'),
    # path('json_filter/', JsonFilterStore.as_view(), name='json_filter'),
    path('store/', StoreView.as_view(), name='store'),
    path('products/<str:category>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('review/<int:pk>/', AddReview.as_view(), name='add_review'),
]

app_users/models.py
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _
from django.db import models


User = get_user_model()


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=_('user'))
    phone_valid = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message=' '.join([str(_('Phone number must be entered in the format:')), '+999999999',
                                                   str(_('Up to 15 digits allowed.'))]))
    phone = models.CharField(max_length=16, verbose_name=_('phone number'), validators=[phone_valid],
                             null=True, blank=True)
    city = models.CharField(max_length=40, verbose_name=_('city'),
                            null=True, blank=True)
    balance = models.DecimalField(max_digits=20, decimal_places=2, verbose_name=_('balance'), default=0)
    loyal_group = models.CharField(max_length=50, verbose_name=_('group of loyalty'), default='None')
    qty_buy = models.PositiveIntegerField(verbose_name=_('quantity buying'), default=0)

    class Meta:
        verbose_name = _('customer')
        verbose_name_plural = _('customers')

    def __str__(self):
        return str(self.user)


class CustomerGroup(models.Model):
    name = models.CharField(_('name'), max_length=50)
    qty_buy = models.PositiveIntegerField()

    class Meta:
        verbose_name = _('group of loyalty')
        verbose_name_plural = _('groups of loyalty')

    def __str__(self):
        return self.name

app_users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _

from .models import Customer


class AuthForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        error_messages = {
            'invalid_login': _("Please enter a correct %(username)s and password. "
                               "Note that both fields may be case-sensitive."),
            'inactive': _("This account is inactive."),
        }


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=40, required=False)
    email = forms.EmailField(max_length=50, required=True)
    city = forms.CharField(max_length=40, localize=True, required=False)
    phone_valid = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message=' '.join([str(_('Phone number must be entered in the format:')), '+999999999',
                                                   str(_('Up to 15 digits allowed.'))]))
    phone = forms.CharField(max_length=17, validators=[phone_valid], required=True)

    class Meta:
        model = User
        fields = [
            'username', 'password1',
            'first_name', 'last_name', 'email',
            'city', 'phone',
        ]


class UpBalanceForm(forms.Form):
    balance = forms.DecimalField(max_digits=20, decimal_places=2, required=True)


class CustomerEditForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=40, required=False)
    email = forms.EmailField(max_length=50, required=True)

    class Meta:
        model = Customer
        fields = [
            'first_name', 'last_name', 'email', 'city', 'phone',
        ]

app_users/views.py
from typing import Callable

from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.core.exceptions import ImproperlyConfigured
from django.db import transaction
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View

from .forms import RegisterForm, UpBalanceForm, CustomerEditForm
from .services import create_customer, edit_customer, edit_balance, get_customer, \
    get_products_in_wishlist, customer_buy_products, write_off_goods, add_to_purchase_history
from shop.mixins import ProductsMixin
import logging


logger = logging.getLogger(__name__)


class UserLogin(LoginView):
    template_name = 'app_users/login.html'
    success_url = '/'

    def get_success_url(self):
        if not self.success_url:
            raise ImproperlyConfigured("No URL to redirect to. Provide a success_url.")
        logger.info(f'User {self.request.user} has authenticate on the site')
        return str(self.success_url)


class UserLogout(LogoutView):
    template_name = 'app_users/logout.html'
    next_page = '/users/login'


class RegisterView(View):
    """
    Страница регистрации нового пользователя
    """
    @classmethod
    def get(cls, request) -> Callable:
        form = RegisterForm()
        return render(request, 'app_users/register.html', context={'form': form})

    @classmethod
    def post(cls, request) -> Callable:
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = create_customer(form=form)
            login(request, user)
            return redirect(reverse('main_page'))
        form = RegisterForm()
        return render(request, 'app_users/register.html', context={'form': form})


class AccountInfoView(LoginRequiredMixin, ProductsMixin, View):
    """
    Информация об аккаунте
    """
    login_url = '/users/login/'
    template_name = 'app_users/customer_account.html'

    def get(self, request) -> Callable:
        context = dict()
        user_id = request.user.id
        user_list = self.get_wishlist(user_id)
        context['customer'] = get_customer(user_id)
        if user_list['wishlist']:
            context['products'] = get_products_in_wishlist(user_list['wishlist'])
            context['wishlist'] = user_list
        else:
            context['products'] = None
            context['wishlist'] = 0
        context = {**context, **self.get_cart(user_id)}
        return render(request, 'app_users/customer_account.html', context=context)


class CheckoutView(LoginRequiredMixin, ProductsMixin, View):
    """
    Страница оплаты товаров в корзине
    """
    login_url = '/users/login/'

    def get(self, request) -> Callable:
        context = self.get_cart(request.user.id, shops=True)
        context = {**context, **self.get_wishlist(request.user.id)}
        return render(request, 'app_users/checkout.html', context=context)


class TopUpBalanceView(LoginRequiredMixin, ProductsMixin, View):
    """
    Страница пополнения баланса
    """
    login_url = '/users/login/'

    def get(self, request) -> Callable:
        context = dict()
        user_id = request.user.id
        context['customer'] = get_customer(user_id=user_id)
        context['form'] = UpBalanceForm()
        context = {**context, **self.get_cart(user_id), **self.get_wishlist(user_id)}
        return render(request, 'app_users/upbalance.html', context=context)

    @classmethod
    def post(cls, request) -> Callable:
        form = UpBalanceForm(request.POST)
        if form.is_valid():
            edit_balance(request, form)
        return redirect(reverse('account'))


class CustomerEditView(LoginRequiredMixin, ProductsMixin, View):
    """
    Страница редактирования профиля
    """
    login_url = '/users/login/'

    def get(self, request) -> Callable:
        context = dict()
        user_id = request.user.id
        context['customer'] = get_customer(user_id=user_id)
        context['form'] = CustomerEditForm()
        context = {**context, **self.get_cart(user_id),
                              **self.get_wishlist(user_id)}
        return render(request, 'app_users/edit_customer_info.html', context=context)

    @classmethod
    def post(cls, request) -> Callable:
        form = CustomerEditForm(request.POST, request.FILES)
        if form.is_valid():
            edit_customer(request, form)
        return redirect(reverse('account'))


class PayOrderView(LoginRequiredMixin, ProductsMixin, View):
    """
    Страница покупки товаров из корзины
    """
    login_url = '/users/login/'

    @classmethod
    def get(cls, request) -> Callable:
        user_id = request.user.id
        customer = get_customer(user_id=user_id)
        context = cls.get_cart(user_id=user_id)
        if context['subtotal'] <= customer.balance:
            with transaction.atomic():
                write_off_goods(request)
                add_to_purchase_history(context['cart'], user_id)
                customer_buy_products(customer, context)
                context['cart'] = cls.clear_cart(user_id=user_id)
                logger.info(f'User {request.user} purchased {context["quantity"]} unit(s)')
        context = {**context, **cls.get_wishlist(user_id=user_id)}
        return render(request, 'app_users/pay_order.html', context=context)

templates/app_users/checkout.html
{% extends 'layout.html' %}
{% load static %}
{% load custom_tags %}
{% load i18n %}

{% block searchbar %}
		{% get_all_categories %}
{% endblock %}

{%block cart_summary %}{% endblock %}
{% block nav %}{% endblock %}

{% block breadcrumb %}
	<li><a href="/">Home</a></li>
	<li><a href="{% url 'account' %}">{% trans 'Account' %}</a></li>
	<li><a href="{% url 'account' %}">{% trans 'My Cart' %}</a></li>
	<li class="active">{% trans 'Checkout' %}</li>
{% endblock %}

{% block content %}
<!-- SECTION -->
<div class="section">
	<!-- container -->
	<div class="container">
		<!-- row -->
		<div class="row">
			<!-- Order Details -->
			<div class="col-md-555 order-details" style="max-width: 600px; margin: auto;">
				<div class="section-title text-center">
					<h3 class="title">{% trans 'Your Order' %}</h3>
				</div>
					<div class="order-summary">
					{% if subtotal %}
					<form method="get" action="{% url 'pay_order' %}" id="orderform">
						<div class="order-col">
							<div style="font-size:20px;"><strong>{% trans 'PRODUCT' %}</strong></div>
							<div style="font-size:20px;"><strong>{% trans 'TOTAL' %}</strong></div>
						</div>
						<div class="order-products">
							{% for item in cart %}
							<div class="order-col" style="position: relative;">
								<div class="order-item">{{item.qty}}x {{item.product.title}}</div>
								<form action="{% url 'delete_from_cart' %}" method="get" id="deleteform">
									<input type="hidden" name="id" value="{{ item.product.id }}" form="deleteform">
									<button class="delete adtnl-del" style="top: 10px;" form="deleteform"><i class="fa fa-close"></i></button>
								</form>
								<div class="order-item">{{item.product.price}} RUB</div>
							</div>
								{% for storage in item.product.related_storage.all %}
								{% if storage.qty >= item.qty %}
								<div class="input-radio">
									<input type="radio" name="{{item.product.slug}}" id="{{storage.id}}" value="{{storage.id}}~{{item.qty}}" form="orderform">
									<label for="{{storage.id}}">
										<span></span>
										{{storage.shop}}
									</label>
									<div class="caption">
										<p class="checkout-item">{% trans 'IN STOCK:' %}
											<span>{{storage.qty}} piece(s)</span>
										</p>
									</div>
								</div>
								{% endif %}
								{% endfor %}
							{% endfor %}
						</div>
						<div class="order-col">
							<div>{% trans 'Shiping' %}</div>
							<div><strong>{% trans 'FREE' %}</strong></div>
						</div>
						<div class="order-col">
							<div style="font-size:20px;"><strong>{% trans 'TOTAL' %}</strong></div>
							<div><strong class="order-total">{{subtotal}} RUB</strong></div>
						</div>
						<div style="display: flex; justify-content:center;">
						<button onclick="return RadioValidator();" class="primary-btn order-submit order-pay" form="orderform">
					{% trans 'Pay by order' %}</button></div>
					</form>
				</div>
				{% else %}
				<h3 class="text-center">{% trans 'There is no products for buy in your cart' %}</h3>
				{% endif %}
			</div>

			<script>
				function RadioValidator()
				{
					var ShowAlert = '';
					var AllFormElements = window.document.getElementById("orderform").elements;
					for (i = 0; i < AllFormElements.length; i++)
					{
						if (AllFormElements[i].type == 'radio')
						{
							var ThisRadio = AllFormElements[i].name;
							var ThisChecked = 'No';
							var AllRadioOptions = document.getElementsByName(ThisRadio);
							for (x = 0; x < AllRadioOptions.length; x++)
							{
								console.log(x)
								 if (AllRadioOptions[x].checked && ThisChecked == 'No')
								 {
									 ThisChecked = 'Yes';
									 break;
								 }
							}
							var AlreadySearched = ShowAlert.indexOf(ThisRadio);
							if (ThisChecked == 'No' && AlreadySearched == -1)
							{
							ShowAlert = 'Need to choice the shop for all products';
							break;
							}
						}
					}
					if (ShowAlert != '')
					{
					alert(ShowAlert);
					return false;
					}
					else
					{
					return true;
					}
				}
			</script>
		</div>
		<!-- /row -->
	</div>
	<!-- /container -->
</div>
<!-- /SECTION -->
{% endblock %}

templates/app_users/customer_account.html
{% extends 'layout.html' %}
{% load static %}
{% load custom_tags %}
{% load i18n %}

{% block searchbar %}
		{% get_all_categories %}
{% endblock %}

{% block breadcrumb %}
	<li><a href="/">{% trans 'Home' %}</a></li>
	<li class="active">{% trans 'Account' %}</li>
{% endblock %}

{% block content %}
<!-- SECTION -->
<div class="section">
	<!-- container -->
	<div class="container">
		<!-- row -->
		<div class="row" >
			<div  style="min-height: 300px; max-width: 600px; margin: auto;">
				<!-- Sign Up -->
				<div class="billing-details text-center">
					<div class="section-title">
						<h3 class="title">{% trans 'Account info' %}</h3>
					</div>
					<div class="d-table">
						<div class="form-group d-tr">
							<p class="d-td">{% trans 'Username:' %}</p>
							<span class="d-td-2">{{request.user.username}}</span>
						</div>
						<div class="form-group d-tr">
							<p class="d-td">{% trans 'First Name:' %}</p>
							<span class="d-td-2">{{request.user.first_name}}</span>
						</div>
						<div class="form-group d-tr">
							<p class="d-td">{% trans 'Last Name:' %}</p>
							<span class="d-td-2">{{request.user.last_name}}</span>
						</div>
						<div class="form-group d-tr">
							<p class="d-td">{% trans 'Phone Number:' %}</p>
							<span class="d-td-2">{{customer.phone}}</span>
						</div>
						<div class="form-group d-tr">
							<p class="d-td">{% trans 'City Location:' %}</p>
							<span class="d-td-2">{{customer.city}}</span>
						</div>
						<div class="form-group d-tr">
							<p class="d-td">{% trans 'Your Status:' %}</p>
							<span class="d-td-2">{{customer.loyal_group}}</span>
						</div>
						<div class="form-group d-tr">
							<p class="d-td">{% trans 'Your Balance:' %}</p>
							<span class="d-td-2">{{customer.balance}} RUB</span>
						</div>
						<div class="form-group d-tr">
							<p class="d-td"><a href="{% url 'edit_info' %}" class="primary-btn order-submit ">{% trans 'Edit info' %}</a></p>
							<p class="d-td"><a href="{% url 'upbalance' %}" class="primary-btn order-submit ">{% trans 'Top up your balance' %}</a></p>
						</div>
					</div>
				</div>
				<!-- /Sign Up -->
			</div>
		</div>
		<!-- /row -->
	</div>
	<!-- /container -->
</div>
<!-- /SECTION -->

<!-- SECTION -->
<div class="section" id="account_cart">
	<!-- container -->
	<div class="container">
		<!-- row -->
		<div class="row">
		<div class="order-details" style="max-width: 600px; margin: auto;">
				<div class="section-title text-center">
					<h3 class="title">{% trans 'Your Cart' %}</h3>
				</div>
				{% if quantity > 0%}
				<div class="order-summary">

					<div class="order-col">
						<div><strong>{% trans 'PRODUCT' %}</strong></div>
						<div><strong>{% trans 'TOTAL' %}</strong></div>
					</div>
					<div class="order-products">
						{% for item in cart %}
						<div class="order-col" style="position: relative;">
							<div class="product-img prt-img-accnt" style="background-image: url('{{ MEDIA_ROOT }}/media/{{ item.product.image }}');"></div>
							<div><a href="{{ item.product.get_absolute_url }}" style="padding-left: 30px;">{{item.qty}}x {{item.product.title}}</a>
								<form action="{% url 'delete_from_cart' %}" method="get">
									<input type="hidden" name="id" value="{{ item.product.id }}">
									<button class="delete adtnl-del"><i class="fa fa-close"></i></button>
								</form>
							</div>
							<div>{{item.product.price}} RUB</div>
						</div>
						{% endfor %}
					</div>
					<div class="order-col">
						<div><strong>{% trans 'TOTAL' %}</strong></div>
						<div><strong class="order-total">{{subtotal}} RUB</strong></div>
					</div>
				</div>
				<div class="text-center">
					<a href="{% url 'checkout' %}" class="primary-btn order-submit" style="display: inline; padding: 15px 70px;">{% trans 'Go to order' %}</a>
				</div>
				{% else %}
				<h3 class="title text-center">{% trans 'Your cart is empty' %}</h3>
				{% endif %}
			</div>
		</div>
		<!-- /row -->
	</div>
	<!-- /container -->
</div>
<!-- /SECTION -->

<!-- SECTION -->
<div class="section" id="account_wishlist">
	<!-- container -->
	<div class="container">
		<!-- row -->
		<div class="row">

			<!-- section title -->
			<div class="col-md-12">
				<div class="section-title text-center">
					<h3 class="title">{% trans 'Your wishlist' %}</h3>
				</div>
			</div>
			<!-- /section title -->

			<!-- Products tab & slick -->
			<div class="col-md-12">
				<div class="row">
					{% if products %}
					<div class="products-tabs">
						<!-- tab -->
						<div id="tab1" class="tab-pane active">
							<div class="products-slick" data-nav="#slick-nav-1">
								<!-- product -->
								{% for product in products %}
								<div class="product">
									<div class="product-img">
										<img src="{{ MEDIA_ROOT }}/media/{{ product.image }}" alt="product_image">
									</div>
									<div class="product-body">
										<p class="product-category">{{ product.category.name }}</p>
										<h3 class="product-name"><a href="{{ product.get_absolute_url }}">{{ product.title}}</a></h3>
										<h4 class="product-price">{{ product.price}}</h4>
										<div class="product-rating">
												{% for i in 5|times %}
													{% if i < product.rating %}
														<i class="fa fa-star"></i>
													{% else %}
														<i class="fa fa-star-o empty"></i>
													{% endif %}
												{% endfor %}
										</div>
										<div class="product-btns">
											<form class="add-to-wishlist-form" method="get" action="{% url 'add_to_wish' %}">
												<button class="add-to-wishlist">
														<input type="hidden" name="id" value="{{ product.id }}">
														<i class="heart-custom"></i>
													<span class="tooltipp">{% trans 'Remove from wishlist' %}</span>
												</button>
											</form>
											<button class="quick-view"><a href="/products/{{ product.category.slug }}/{{product.slug}}"><i class="fa fa-eye"></i></a><span class="tooltipp">{% trans 'quick view' %}</span></button>
										</div>
									</div>
									<div class="add-to-cart">
										<form method="get" action="{% url 'add_to_cart' %}">
											<input type="hidden" name="id" value="{{ product.id }}">
											<button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> {% trans 'add to cart' %}</button>
										</form>
									</div>
								</div>
								<!-- /product -->
								{% endfor %}
							</div>
							<div id="slick-nav-1" class="products-slick-nav"></div>
						</div>
						<!-- /tab -->
						{% else %}
							<h3 class="title text-center">{% trans 'Your wishlist is empty' %}</h3>
						{% endif %}
					</div>
				</div>
			</div>
			<!-- Products tab & slick -->
		</div>
		<!-- /row -->
	</div>
	<!-- /container -->
</div>
<!-- /SECTION -->
{% endblock %}

templates/app_users/edit_customer_info.html
{% extends 'layout.html' %}
{% load static %}
{% load custom_tags %}
{% load i18n %}

{% block searchbar %}
		{% get_all_categories %}
{% endblock %}

{% block breadcrumb %}
	<li><a href="/">{% trans 'Home' %}</a></li>
	<li><a href="{% url 'account' %}">{% trans 'Account' %}</a></li>
	<li class="active">{% trans 'Edit' %}</li>
{% endblock %}

{% block content %}
<!-- SECTION -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row" style="min-height: 300px;">
            <div class="col-md-7">
                <!-- Sign Up -->
                <div class="billing-details">
                    <div class="section-title">
                        <h3 class="title">{% trans 'Edit Customer Info' %}</h3>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <input class="input" type="text" name="first_name" maxlength="30" value="{{customer.user.first_name}}" id="id_first_name" placeholder="{% trans 'Your First Name' %}">
                        </div>
                        <div class="form-group">
                            <input class="input" type="text" name="last_name" maxlength="40" value="{{customer.user.last_name}}" id="id_last_name" placeholder="{% trans 'Your Last Name' %}">
                        </div>
                        <div class="form-group">
                            <input class="input" type="email" name="email" maxlength="50" value="{{customer.user.email}}" id="id_email" placeholder="*{% trans 'Your E-mail' %}">
                        </div>
                        <div class="form-group">
                            <input class="input" name="phone" maxlength="20" required="" value="{{customer.phone}}" id="id_phone" placeholder="*{% trans 'Your Phone Number' %}">
                        </div>
                        <div class="form-group">
                            <input class="input" type="text" name="city" maxlength="40" value="{{customer.city}}" id="id_city" placeholder="{% trans 'Your City Location' %}">
                        </div>

                        <div style="display: flex; justify-content: space-evenly;">
                            <button type="submit" class="primary-btn order-submit">{% trans 'Accept changes' %}</button>
                        </div>
                    </form>
                </div>
                <!-- /Sign Up -->
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /SECTION -->
{% endblock %}

templates/app_users/register.html
{% extends 'layout.html' %}
{% load static %}
{% load custom_tags %}
{% load i18n %}

{% block searchbar %}
		{% get_all_categories %}
{% endblock %}

{% block breadcrumb %}
	<li><a href="/">{% trans 'Home' %}</a></li>
	<li class="active">{% trans 'Registration' %}</li>
{% endblock %}

{% block content %}
		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row" style="min-height: 300px;">
                    <div class="col-md-7">
						<!-- Sign Up -->
						<div class="billing-details">
							<div class="section-title">
								<h3 class="title">{% trans 'Registration new customer' %}</h3>
							</div>
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group">

                                    <input class="input" type="text" name="username" maxlength="150" autofocus required id="id_username" placeholder="*{% trans 'Enter Username' %}">
                                </div>
                                <div class="form-group">
                                    <input class="input" type="text" name="first_name" maxlength="30" id="id_first_name" placeholder="{% trans 'Your First Name' %}">
                                </div>
                                <div class="form-group">
                                    <input class="input" type="text" name="last_name" maxlength="40" id="id_last_name" placeholder="{% trans 'Your Last Name' %}">
                                </div>
                                <div class="form-group">
                                    <input class="input" type="password" name="password1" autocomplete="new-password" required id="id_password1" placeholder="*{% trans 'Enter Password' %}">
                                </div>
                                <div class="form-group">
                                    <input class="input" type="password" name="password2" autocomplete="new-password" required id="id_password2" placeholder="*{% trans 'Confirm Password' %}">
                                </div>
                                <div class="form-group">
                                    <input class="input" type="email" name="email" maxlength="50" id="id_email" placeholder="*{% trans 'Your E-mail' %}">
                                </div>
                                <div class="form-group">
                                    <input class="input" name="phone" maxlength="20" required="" id="id_phone" placeholder="*{% trans 'Your Phone Number' %}">
                                </div>
                                <div class="form-group">
                                    <input class="input" type="text" name="city" maxlength="40" id="id_city" placeholder="{% trans 'Your City Location' %}">
                                </div>

                                <div style="display: flex; justify-content: space-evenly;">
                                    <button type="submit" class="primary-btn order-submit">{% trans 'Register' %}</button>
                                    <a href="{% url 'login' %}" class="primary-btn order-submit">{% trans 'Sigh up' %}</a>
                                </div>
                            </form>
						</div>
						<!-- /Sign Up -->
                    </div>
                </div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->
{% endblock %}

templates/app_users/upbalance.html
{% extends 'layout.html' %}
{% load static %}
{% load custom_tags %}
{% load i18n %}

{% block searchbar %}
		{% get_all_categories %}
{% endblock %}

{% block breadcrumb %}
	<li><a href="/">{% trans 'Home' %}</a></li>
	<li><a href="{% url 'account' %}">{% trans 'Account' %}</a></li>
	<li>{% trans 'Edit' %}</li>
	<li class="active">{% trans 'Change Balance' %}</li>
{% endblock %}

{% block content %}
<!-- SECTION -->
<div class="section">
	<!-- container -->
	<div class="container">
		<!-- row -->
		<div class="row" style="min-height: 300px;">
			<div class="col-md-7">
				<!-- Sign Up -->
				<div class="billing-details">
					<div class="section-title">
						<h3 class="title">{% trans 'Change your balance' %}</h3>
					</div>
					<div style="margin-bottom: 30px;">
						<p style="font-size: 18px; line-height: 18px; font-weight: 500;">{% trans 'Now your balance:' %}  <span style="color: red;">{{customer.balance}} RUB</span></p>
					</div>
					<form method="post">
						{% csrf_token %}
						<div class="form-group">
							<input class="input" type="number" name="balance" required id="id_balance" placeholder="{% trans 'Enter the amount to add more money' %}">
						</div>

						<div style="display: flex; justify-content: space-evenly;">
							<button type="submit" class="primary-btn order-submit">{% trans 'Submit' %}</button>

						</div>
					</form>
				</div>
				<!-- /Sign Up -->
			</div>
		</div>
		<!-- /row -->
	</div>
	<!-- /container -->
</div>
		<!-- /SECTION -->
{% endblock %}